### ISSUE TITLE
Do you plan to release the code? 

### ISSUE THREAD

**Issue by TontonTremblay** [paulpanwang/POPE#1]
I see that most of this repo so far does not have code to run POPE, do you have plans in the future to release.

**Comment by paulpanwang** [comment]
Thank you for your attention. We will definitely open-source the code. We are currently reviewing and organizing the code and will provide the code as soon as possible.

**Comment by ttsesm** [comment]
@paulpanwang do you have any ETA about when you will be able to make the code available?

Thanks.

**Comment by Ale-Burzio** [comment]
@paulpanwang great work! any rough idea of when the full code is going to be released?

**Comment by hiyyg** [comment]
Any updates?

**Comment by paulpanwang** [comment]
Thank you for your attention. We apologize for the delayed response due to a heavy workload at the company. We are gradually updating the code corresponding to the paper. If you are interested in any specific part, please feel free to raise an issue.

**Comment by paulpanwang** [comment]
Thank you for your attention.  If you are interested in any specific part, please feel free to raise an issue.
