### ISSUE TITLE
The generation of data pairs

### ISSUE THREAD

**Issue by shanice-l** [paulpanwang/POPE#4]
Thank you for making the awesome project open-source!

I've noticed that the data pairs are pre-defined in the JSON files (like [LMO](https://github.com/paulpanwang/POPE/blob/main/data/pairs/LINEMOD-test.json)). So how do you generate these data pairs, by random or according to some principles?

Looking forward to your reply.

**Comment by frickyinn** [comment]
Only one sentence in 4.1 Evaluation Setup

> As the pose distribution in different datasets varies, we organize the manage the test set in a balanced distribution from 0◦ to 30◦.

**Comment by paulpanwang** [comment]
Thank you for your attention. We will upload the processed dataset to the [Hugging Face website](https://huggingface.co/datasets/paulpanwang/POPE_Dataset/tree/main).

**Comment by paulpanwang** [comment]
Thank you for your attention. We will upload the processed dataset to the [Hugging Face website](https://huggingface.co/datasets/paulpanwang/POPE_Dataset/tree/main).

**Comment by werdnabae** [comment]
You still didn't really answer the question, how were these data pairs defined?
